# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

enable_passive: true
passive_key: CTRL
# options for toggle_key: CTRL, ALT, SHIFT, META, LEFT_CTRL, LEFT_ALT, LEFT_SHIFT, 
#                         LEFT_META, RIGHT_CTRL, RIGHT_ALT, RIGHT_SHIFT, RIGHT_META, OFF
toggle_key: RIGHT_ALT


matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
